/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2018-05-02.5788226"
#define SSHVER "PuTTY-Snapshot-2018-05-02.5788226"
#define BINARY_VERSION 0,70,1302,0
#define SOURCE_COMMIT "5788226460c10f76c2a29eed2a08b26390c67c26"
